### ISSUE TITLE
Fetching historic data API problem

### ISSUE THREAD

**Issue by dlainfiesta** [barchart/barchart-ondemand-client-python#4]
Hi, 

I was trying to use the API with Anaconda/Spyder/Python 3.6, was able finally to install it, but the code fetches nothing: 

Input:
resp = od.history('APPL', 'daily', maxRecors = 50, interval = 1)
print('getHistory', resp)

Output: 
getHistory {'status': {'code': 204, 'message': 'Success, but no content to return.'}, 'results': None}

Is the API able to download historic data from stocks and options?

**Comment by mvberg** [comment]
@dlainfiesta hm, i'm assuming you are using the free API? the free API has limited access to historical data, but yes, the full API has historical data for futures, stocks, futures and stock options, crypto, etc.

running the below in my [Google Colab Notebook](https://colab.research.google.com/), i am seeing no issues...

```python
import ondemand
import pandas as pd
from datetime import datetime


od = ondemand.OnDemandClient(api_key="KEY", 
  end_point='https://marketdata.websol.barchart.com/')

resp = od.history('AAPL', 'minutes', maxRecords=50, interval=1)['results']

print(resp)
prices = [bar['close'] for bar in resp]
dates = [datetime.strptime(bar['timestamp'][:19], '%Y-%m-%dT%H:%M:%S') for bar in resp]

data = pd.Series(prices, index=dates)

data.plot()
print(prices)
```

![python_notebook](https://user-images.githubusercontent.com/649509/48010084-8695e000-e0e2-11e8-88cc-22ec8bf11504.jpg)

do you have a runnable notebook you can share?

**Comment by dlainfiesta** [comment]
Hi, thanks for the rapid response. I was able to run your code, no problem, but I am interested in daily data, sorry for not specifying it previously. 

import ondemand
import pandas as pd
from datetime import datetime

od = ondemand.OnDemandClient(api_key= key, end_point='https://marketdata.websol.barchart.com/')

resp = od.history('TSLA', 'daily', maxRecords=100, interval=1)['results']

print(resp)
prices = [bar['close'] for bar in resp]
dates = [datetime.strptime(bar['timestamp'][:19], '%Y-%m-%dT%H:%M:%S') for bar in resp]

data = pd.Series(prices, index=dates)

fig = plt.figure()
plt.plot(data)
plt.show()

Here in this case, you can see how it only fetches one value. :(

print(prices)

**Comment by mvberg** [comment]
ah, ok - so in the case of Daily you need to set the `startDate` (YYYYMMDD) param

```python
resp = od.history('AAPL', 'daily', startDate='20180601')['results']
```

please see full `getHistory` documentation and request params here: https://www.barchart.com/ondemand/api/getHistory/free 

@dlainfiesta

**Comment by dlainfiesta** [comment]
Hi, 

Now it worked, no problem! Thanks a lot! Where can I find documentation about the syntaxis regarding each form of gathering data with the API? Daily, quote...

**Comment by dlainfiesta** [comment]
Hi,

Now it worked, no problem! Thanks a lot! Where can I find documentation about the syntaxis regarding each form of gathering data with the API? Daily, quote...
