### ISSUE TITLE
issues running ondemand and client modules

### ISSUE THREAD

**Issue by hkml** [barchart/barchart-ondemand-client-python#5]
I have subscribed to BarChart's getCmdtyStats API and have tried to use it. I am not able to run even the sample code from the BarChart website. The client module is not showing up in the filefolder with all other Python site-packages. However, when I run pip list in my CMD, Client shows that it is present. I am trying to run the code through Anaconda 3 and the Spyder IDE. 
I have added picture showing the cmd, site-packages folder and IDE error code. 
Any idea on how to fix this? 
![2019-02-23 5](https://user-images.githubusercontent.com/45409609/53284031-4342a880-3789-11e9-8414-5c0716b147fd.png)

**Comment by mvberg** [comment]
hi @hkml appears that you are trying to use a SOAP client - not this project.

this project is a Python client library for Barchart OnDemand.

You can see a live example of this library in this Python Notebook:

https://colab.research.google.com/drive/1D8389Q8qQzbppqFxwpUOobheZ2jb3Gp4

In this library, what you would want is something like:

```
resp = od.get('getCmdtyStats', symbol='USDA-SOYB-PROD-MS-96.CM')
```
